TTLocalizer: Running in language: English
OTPLocalizer: Running in language: English
Preloading suits...
Traceback (most recent call last):
  File "C:\Users\Josh\Documents\Toontown Empire\Toontown Empire\Toontown Empire\src\dependencies\panda\python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Josh\Documents\Toontown Empire\Toontown Empire\Toontown Empire\src\dependencies\panda\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Josh\Documents\Toontown Empire\Toontown Empire\Toontown Empire\src\toontown\toonbase\ClientStart.py", line 156, in <module>
    from toontown.distributed import ToontownClientRepository
  File "toontown\distributed\ToontownClientRepository.py", line 17, in <module>
    from otp.distributed import OTPClientRepository
  File "otp\distributed\OTPClientRepository.py", line 13, in <module>
    from otp.avatar.DistributedPlayer import DistributedPlayer
  File "otp\avatar\DistributedPlayer.py", line 20, in <module>
    class DistributedPlayer(DistributedAvatar.DistributedAvatar, PlayerBase.PlayerBase, TelemetryLimited):
  File "otp\avatar\DistributedPlayer.py", line 22, in DistributedPlayer
    chatGarbler = ChatGarbler.ChatGarbler()
TypeError: __init__() takes exactly 2 arguments (1 given)
